### ISSUE TITLE
Office 365 OWA AutocompleteCache not clearning

### ISSUE THREAD

**Issue by ShreedharEtte** [michelderooij/Clear-AutoComplete#1]
Hi Michel,

Thank you for writing the script.

I was able to clear run the script and able to clear the Outlook Autocomplete.

However, get message "No OWA AutoComplete item found" for OWA.

Please share your thoughts.

**Comment by queks** [comment]
I'm having the same issue. For users that only have OWA access, there is no ability to clear the cache otherwise, but it appears the script is not working for OWA.

**Comment by michelderooij** [comment]
Validated and found working. Also make sure you are refreshing pages as the DHTML app might cache information as well.
