### ISSUE TITLE
Cannot find an overload for "Bind" and the argument count: "2"

### ISSUE THREAD

**Issue by mrblwd** [michelderooij/Clear-AutoComplete#2]
Hi there, i'm using your script to remove all the AutoComplete suggestions in Outlook for all mailboxes. I setup the impersonation management role and that seems to work. 

I receive the following error:

Command:

`.\Clear-AutoComplete.ps1 -Identity "username" -Type All -Verbose -Server mailserver/EWS/Exchange.asmx `

Error:

`VERBOSE: Loading C:\Program Files\Microsoft\Exchange\Web Services\2.2\Microsoft.Exchange.WebServices.dll
VERBOSE: Loaded Microsoft.Exchange.WebServices v15.0.0.0
VERBOSE: Set to trust all certificates
Processing mailbox alias@upn.nl
VERBOSE: Using Exchange Web Services URL https://mailserver/EWS/Exchange.asmx/EWS/Exchange.asmx
Processing AutoComplete stream for alias@upn.nl
Cannot find an overload for "Bind" and the argument count: "2".
At C:\Library\Clear-AutoComplete.ps1:206 char:9
+         $InboxFolder= [Microsoft.Exchange.WebServices.Data.Folder]::B ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

New-Object : Cannot find an overload for "IsEqualTo" and the argument count: "2".
At C:\Library\Clear-AutoComplete.ps1:207 char:38
+ ... Collection= New-Object Microsoft.Exchange.WebServices.Data.SearchFilt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At C:\Library\Clear-AutoComplete.ps1:211 char:9
+         $ItemSearchResults= $InboxFolder.FindItems( $ItemSearchFilter ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

No AutoComplete Stream item found
Processing OWA AutoComplete for alias@upn.nl
No OWA AutoComplete item found
Processing SuggestedContacts for alias@upn.nl
New-Object : Cannot find an overload for "IsEqualTo" and the argument count: "2".
At C:\Library\Clear-AutoComplete.ps1:292 char:30
+ ... archFilter= New-Object Microsoft.Exchange.WebServices.Data.SearchFilt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

Cannot find an overload for "FindFolders" and the argument count: "3".
At C:\Library\Clear-AutoComplete.ps1:293 char:9
+         $FolderSearchResults= $EwsService.FindFolders( $FolderId, $Fo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

No Suggested Contacts folder found
Processing RecipientCache for alias@upn.nl
No RecipientCache folder found`

Is there a way to fix this?

Thanks

**Comment by michelderooij** [comment]
Use more recent version of Exchange Web Services DLL.
