### ISSUE TITLE
How is your environment set up to run this?

### ISSUE THREAD

**Issue by explody** [michelderooij/Clear-AutoComplete#3]
Very experienced systems folks, but Windows dev noobs here, trying to get this to run.

We've got down a rat hole of trying to find older installers for e.g. EWS, Microsoft Identity Client, etc etc.  It's not entirely what or how things should be installed.  We made it past several DLL dependencies but are stuck on one about Microsoft.IdentityModel.Abstractions (we have to use oauth now).

Would you be willing to give an overview of what you have set up to run this?

Thanks!

**Comment by michelderooij** [comment]
EWS.Managed.API and Microsoft.Identity.Client are available as NuGet package, see https://eightwone.com/2020/10/05/ews-webservices-managed-api/. That should install the proper libraries for you, after which you can use the script with OAuth.
For OAuth, you need TenantId, ClientId (of the registered App) and either Secret or one or more Certificate parameters depending on if you have it available/installed etc.
